[package]
name = "exon"
version = "0.31.0"
description = "A package manager for C++"
authors = ["Geunryeol Park (misut)"]
license = "MIT"
type = "bin"
standard = 23

[dependencies]
"github.com/misut/cppx" = "1.10.0"
"github.com/misut/tomlcpp" = "0.3.0"
