[plugins]
exon = "https://github.com/misut/mise-exon.git"
intron = "https://github.com/misut/mise-intron.git"

[tools]
clang = "latest"
cmake = "latest"
exon = "0.10.1"
intron = "0.9.0"
ninja = "latest"
